/// @description Insert description here
// You can write your code in this editor

draw_self();
var text;
switch title {
	case "Power" :
		text = "Power increases the Damage done by your Attacks.";
		break;
	case "Speed" :
		text = "Speed increases the Block generated by your skills.";
		break;
	case "Disrupt" :
		text = "Disrupt allows you to stun an enemy either by dealing damage with a skill with disrupt, or fully blocking Incoming Damage.";
		break;
	case "Reroll" :
		text = "Reroll allows you to reroll a die to be used again. (Right Click one of your dice before activation.)";
		break;
	case "Drain" :
		text = "A skill with drain will heal the user for all unblocked damage.";
		break;
	case "Disable" :
		text = "Disable allows you to deplete an enemy's dice.  (Right Click an opponent's die before activation.)";
		break;
	case "Stat0" :
		text = "Attack, Defend, and Dodge will increase the skill cost of Red, Blue, or Green Pips on all skills.";
		break;
				
	case "Stat1" :
		text = "Power increases the Damage done by your Attacks.";
		break;
	case "Stat2" :
		text = "Speed increases the Block generated by your skills.";
		break;
	case "Stat3" :
		text = "Sp Power increases any Magical Skills (Damage or Armor), defined by having a Gold Pip in its cost.";
		break;
	default:
		text = "";
		break;
}
draw_set_font(fnt_explain);
draw_text_ext(x + 5, y + 5, text, string_height("M") + 2, 270);
draw_set_font(fnt_main);